apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookify
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookify
  template:
    metadata:
      labels:
        app: bookify
    spec:
      containers:
      - name: bookify
        image: gcr.io/[PROJECT_ID]/bookify-nextjs:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          value: "8702e4e8-5877-4969-89e6-c2800943b9d8"
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          value: "bookify-rudra-smit"
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          value: "bookify-rudra-smit.firebaseapp.com"
        - name: NEXT_PUBLIC_FIREBASE_DATABASE_URL
          value: "https://bookify-rudra-smit.firebaseio.com"
